server:
  servlet:
    context-path: "/portal"
  port: "8091"

loan-system-api:
  protocol: "http"
  host: "localhost"
  port: "8090"
  baseUri: "/loanms"

payment-process-api:
  protocol: "http"
  host: "localhost"
  port: "8090"
  baseUri: "/paymentms"