server:
  servlet:
    context-path: "/portal"
  port: "8091"

loan-system-api:
  local:
    protocol: "http"
    host: "localhost"
    port: "8090"
    baseUri: "/loanms"
  mock:
    protocol: "https"
    host: "31418c73-a5d9-44de-b75b-aa15d92b6199.mock.pstmn.io"
    port: "443"
    basePath: ""
payment-process-api:
  local:
    protocol: "http"
    host: "localhost"
    port: "8090"
    baseUri: "/paymentms"