server:
  servlet:
    context-path: "/portal"
  port: "8090"

loan-system-api:
  local:
    protocol: "http"
    host: "${LOAN_SYSTEM_API_HOST}"
    port: "8090"
    basePath: "/loanms"
  mock:
    protocol: "https"
    host: "c243fe3c-3651-4cc5-8791-033a5704a5af.mock.pstmn.io"
    port: "443"
    basePath: ""
payment-process-api:
  local:
    protocol: "http"
    host: "${PAYMENT_PROCESS_API_HOST}"
    port: "8090"
    basePath: "/paymentms"
  mock:
    protocol: "https"
    host: "82268936-af08-4840-a6c8-eb05f9ce9f33.mock.pstmn.io"
    port: "443"
    basePath: ""